name: test-build && deploy
on:
  workflow_dispatch:
    inputs:
      DOCKERHUB_USERNAME:
        default: ohdat123
        type: string
      DOCKERHUB_REPO:
        type: string
        default: ohdat
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        default: ohdat123
        type: string
      DOCKERHUB_REPO:
        type: string
        default: ohdat
      VERSION:
        type: string
        default: v0.1.${{ github.run_number }}
    outputs:
      image:
        description: "The image of docker build tag"
        value: ${{ jobs.build.outputs.image }}
      version:
        value: ${{ inputs.VERSION }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TAG: ${{ inputs.DOCKERHUB_REPO }}/${{ github.event.repository.name }}:${{ inputs.VERSION || format('v0.1.{0}', github.run_number) }}
      LATEST_TAG: ${{ inputs.DOCKERHUB_REPO }}/${{ github.event.repository.name }}:latest
    outputs:
      image: ${{ env.TAG }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # - run: echo ${{env.TAG}}
      - run: npm install
      - run: npm run build
      # - name: yarn install && build
      #   run: |
      #     yarn
      #     yarn build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAG }},${{ env.LATEST_TAG }}
  deploy:
    needs: build
    uses: ohdat/actions/.github/workflows/helm-cd.yml@master
    strategy:
      matrix:
        include:
          - helm: ${{ github.event.repository.name }} ohdat/website
            set: "image.repository=${{ needs.build.outputs.image}},resources=null,gateway.hosts[0]=${{ github.event.repository.name }}.dev.catgpt.chat"

    with:
      environment: develop
      kubename: ohdat-dev
      namespace: dev-website
      helm: ${{ matrix.helm }}
      set: ${{ matrix.set }}
      helm-repo: https://ohdat.github.io/helm-template/
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AK }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SK }}
